### ISSUE TITLE
When running it only show Equation Solver and no function

### ISSUE THREAD

**Issue by chongbaolong** [sabari205/Equation-solver#11]
![1](https://github.com/sabari205/Equation-Solver/assets/108920556/414707a0-c391-43c8-ac30-e5bead6ecf61)

**Comment by chongbaolong** [comment]
Can someone record a video to show us about how to run this application? I have tried several times but still cannot work.

**Comment by surajsubramanian** [comment]
Looks weird. Could you try out setting it up using docker-compose? I've made some commits that hopefully make setting this up easier.
Good luck !
