### ISSUE TITLE
Not showing any output

### ISSUE THREAD

**Issue by Sanjeev-Boppidi** [sabari205/Equation-solver#3]
When we enter an equation using the upload option or drawing box, even after clicking save and evaluate we cant find any output.

**Comment by Nagashree-Bhat** [comment]
Flask environment is not working properly.

**Comment by SurajSubramanian** [comment]
Unfortunately, some of the npm packages used at the time of writing this code(about 2 years back) have been deprecated. Feel free to create a merge request if you can figure it out.

**Comment by surajsubramanian** [comment]
Thanks for raising an issue. The error was due to the outdated code and issues with dependencies(originally written around 2 years back)

Code has been updated and the application has now been deployed live too: https://surajsubramanian.github.io/equations-solver/
