### ISSUE TITLE
when running its showing like this

### ISSUE THREAD

**Issue by ebin1999shaji** [sabari205/Equation-solver#7]
![image](https://user-images.githubusercontent.com/124781495/223941846-123cf81d-8cd9-4646-b50c-33f033616677.png)

**Comment by ebin1999shaji** [comment]
which version of node you are using
![image](https://user-images.githubusercontent.com/124781495/223943259-a8fb5270-d9b2-4dfa-a1ea-456706542a25.png)

**Comment by surajsubramanian** [comment]
@ebin1999shaji Sorry for the late reply, I tested it out and it works for me with the version: `v16.15.1` which I have on my machine.
Sorry for not including an `engine -> node` section in the package.json.

If you had to make any changes to get it working, feel free to raise a PR!
