### ISSUE TITLE
Connecting React with Flask

### ISSUE THREAD

**Issue by bushar9414** [sabari205/Equation-solver#8]
Hi ,
Can anyone please help me understand how to connect the frontend with backend? I am trying to set this up locally but the answers are not being shown/calculated.

**Comment by ghost** [comment]
Ask ChatGpt, it has better source to make you understand you well

**Comment by surajsubramanian** [comment]
@bushar9414 sorry for the late reply,
we send POST requests from the Frontend - ReactJS [here](https://github.com/sabari205/Equation-Solver/blob/ec6c531a82f8cd486a53c459b7b6ac7e135ab108/src/Canvas.js#L33) and the backend is a Flask server - [here](https://github.com/sabari205/Equation-Solver/blob/ec6c531a82f8cd486a53c459b7b6ac7e135ab108/Equation-Solver/app.py#L62)
Hope that helps, if you had to make any fixes to get it working feel free to create a PR for them. This project was originally created 3 years back.

And ofcourse, ChatGPT will help you understand much better! 😄
